steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      [
        "build",
        "-t",
        "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/backend-foedtra:$SHORT_SHA",
        "-t",
        "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/backend-foedtra:latest",
        "."
      ]