steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/backend-foedtra:$SHORT_SHA",
        "-t",
        "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/backend-foedtra:latest",
        ".",
      ]
  # push container image to  to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/backend-foedtra"]
  # to deploy container
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "backend-foedtra",
        "--project",
        "${_PROJECT_NAME}",
        "--platform",
        "managed",
        "--region",
        "${_REGION}",
        "--image",
        "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/backend-foedtra:$SHORT_SHA",
        "--port",
        "8080",
        "--allow-unauthenticated",
      ]
options:
  logging: CLOUD_LOGGING_ONLY